### ISSUE TITLE
Unicode decoding midi bytes

### ISSUE THREAD

**Issue by marekzidek** [FlatIO/api-client-python#1]
I think I've found a problem with getting revision_data as midi. Tried other formats, and they work okay, so I'll just convert it to midi, but just to let you know:

I screened the error message and a callstack , where the first call is in my code, and the rest of the nested calls are in flat_api.

![image](https://user-images.githubusercontent.com/13591225/43004271-8300c62e-8c2f-11e8-87ca-c6fba6993897.png)

![image](https://user-images.githubusercontent.com/13591225/43004468-2aa20640-8c30-11e8-9857-c955e06feff4.png)

**Comment by marekzidek** [comment]
Seems like a problem with all binaries, I've just tried mp3 with the same problem, though json and xml work okay.

**Comment by gierschv** [comment]
Thanks for the feedback, I guess the client should keep the response data as `bytes` in this case, instead of trying to decode it [here](https://github.com/FlatIO/api-client-python/blob/391455b9d1a67bb9f389ecf9366b5511a863fce7/flat_api/rest.py#L222). I will make some tests for this bug, we can probably make a PR upstream for that.

**Comment by gierschv** [comment]
Bug fixed in 0.8.1 (https://pypi.org/project/flat-api/0.8.1/)
